name: Android Debug

on:
  push:
    branches: [ main, develop, feature/**, fix/** ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install deps
        run: npm ci --no-audit --no-fund
      - name: Configure local.properties
        run: |
          echo sdk.dir=%LOCALAPPDATA%\\Android\\Sdk > android\\local.properties
      - name: Build Debug
        working-directory: android
        run: .\\gradlew.bat assembleDebug --no-daemon --warning-mode all
